#!/usr/bin/sh

if [ "$DEBUG" = true ] ; then
    yes | vdirsyncer discover -vdebug
    vdirsyncer metasync -vdebug
    vdirsyncer sync -vdebug
    else
    yes | vdirsyncer discover
    vdirsyncer metasync
    vdirsyncer sync
fi

