#!/usr/bin/sh

if [ -z "$VERBOSITY" ]; then
    yes | vdirsyncer discover
    vdirsyncer metasync
    vdirsyncer sync
    else
    yes | vdirsyncer --verbosity=$VERBOSITY discover
    vdirsyncer --verbosity=$VERBOSITY metasync
    vdirsyncer --verbosity=$VERBOSITY sync
fi

